#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
# sensor drivers
obj-$(CONFIG_SENSORS_AK09911)           += akm09911/
obj-$(CONFIG_SENSORS_KXTJ2_FE170CG)     += kxtj2_fe170cg/
obj-$(CONFIG_SENSORS_TF103_KXTJ2)       += kxtj2_tf103/
obj-$(CONFIG_SENSORS_TF103_AK09911)     += akm09911_tf103/

